CREATE TABLE IF NOT EXISTS events (
    "event_id" int primary key,
    "server_received_time" timestamp,
    "app" int,
    "device_carrier" text,
    "$schema"int,
    "city" text,
    "uuid" uuid,
    "user_id" text,
    "event_time" timestamp,
    "platform" text,
    "os_version" text,
    "amplitude_id" bigint,
    "processed_time" timestamp, 
    "user_creation_time" timestamp,
    "version_name" text,
    "ip_address" text,
    "paying" boolean,
    "dma" text,
    "group_properties" json,
    "user_properties" json,
    "client_upload_time" timestamp,
    "$insert_id" text,
    "event_type" text,
    "library"text,
    "amplitude_attribution_ids" text,
    "device_type" text,
    "device_manufacturer" text,
    "start_version" text,
    "location_lng" float,
    "server_upload_time" timestamp,
    "location_lat" float,
    "os_name" text,
    "amplitude_event_type" text,
    "device_brand" text,
    "groups" json,
    "event_properties" json,
    "data" json,
    "device_id" text,
    "language" text,
    "device_model" text,
    "country" text,
    "region" text,
    "is_attribution_event" boolean,
    "adid" text,
    "session_id" bigint,
    "device_family" text,
    "sample_rate" text,
    "idfa" text,
    "client_event_time" timestamp
);