create table inserts (
                    [$insert_id] varchar(64) primary key,
                    [server_received_time] datetime2,
                    [app] int,
                    [device_carrier] varchar(128),
                    [$schema] int,
                    [city] varchar(128),
                    [user_id] varchar(64),
                    [uuid] varchar(64),
                    [event_time] datetime2,
                    [platform] varchar(64),
                    [os_version] varchar(64),
                    [amplitude_id] bigint,
                    [processed_time] datetime2,
                    [user_creation_time] datetime2,
                    [version_name] varchar(64),
                    [ip_address] varchar(32),
                    [paying] bit,
                    [dma] varchar(128),
                    [client_upload_time] datetime2,
                    [event_type] varchar(128),
                    [library] varchar(128),
                    [amplitude_attribution_ids] varchar(64),
                    [device_type] varchar(64),
                    [device_manufacturer] varchar(64),
                    [start_version] varchar(64),
                    [location_lat] real,
                    [location_lng] real,
                    [server_upload_time] datetime2,
                    [event_id] int,
                    [os_name] varchar(64),
                    [amplitude_event_type] varchar(64),
                    [device_brand] varchar(64),
                    [device_id] varchar(64),
                    [language] varchar(64),
                    [device_model] varchar(64),
                    [country] varchar(64),
                    [region] varchar(64),
                    [is_attribution_event] bit,
                    [adid] varchar(64),
                    [session_id] bigint,
                    [device_family] varchar(64),
                    [idfa] varchar(64),
                    [client_event_time] datetime2
                    );

create table users (
    [user_id] varchar(64) primary key,
    [all_companies] varchar(128),
    [company.id] varchar(64),
    [company.name] varchar(64),
    [company.status] varchar(128),
    [email] varchar(128),
);

create table events (
    [event_id] varchar(64) primary key,
    [issuer] varchar(128),
    [name] varchar(128),
    [pageName] varchar(128),
    [path] varchar(512),
    [search] varchar(512),
    [referrer] varchar(512),
    [title] varchar(128),
    [url] varchar(512)
);

